#
# Project NuriKit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true
