#
# Project nurikit - Copyright 2024 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

version: 2

submodules:
  include: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"
  apt_packages:
    - build-essential
    - cmake
    - ninja-build
    - libeigen3-dev
    - doxygen
    - graphviz
  jobs:
    pre_install:
      - |
        cmake -S . -B pre-install -G Ninja \
          -DCMAKE_BUILD_TYPE=Debug -DNURI_BUILD_PYTHON=ON
    post_install:
      - cmake --build pre-install --target clean
    pre_build:
      - |
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - cmake --build build --target nuri_docs

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: "python/docs/conf.py"
