#
# Project NuriKit - Copyright 2025 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Build C++ library

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            arch: x86_64
            runs-on: ubuntu-latest
          - os: macosx
            arch: universal2
            runs-on: macos-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
      - if: ${{ matrix.os == 'macosx' }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: lukka/get-cmake@latest
        with:
          # Ubuntu 22.04 uses 3.22
          # Automatic ctest parallelism from 3.29
          cmakeVersion: "~3.29"

      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist

      - run: |
          cd dist && tar -xf *.tar* -C . --strip-components=1
          echo "NURI_VERSION=$NURI_VERSION" >>"$GITHUB_ENV"
        env:
          NURI_VERSION: ${{ inputs.version }}

      - if: ${{ matrix.os == 'linux' }}
        run: |
          sudo docker run --rm -v "$PWD:/work" -w /work \
            quay.io/pypa/manylinux2014_x86_64:latest \
            .github/scripts/build-lib.sh ${{ matrix.os }}_${{ matrix.arch }}

      - if: ${{ matrix.os == 'macosx' }}
        run: .github/scripts/build-lib.sh ${{ matrix.os }}_${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: libnuri-${{ matrix.os }}
          path: libnuri-*.tar.gz
