#
# Project nurikit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Run clang tools

on:
  workflow_call:
    inputs:
      files-changed-only:
        type: boolean
        default: true
      force:
        type: boolean
        default: false
      version:
        type: string
        default: "17"

defaults:
  run:
    shell: bash

jobs:
  check-want-lint:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/_check-want-test.yaml
    with:
      keyword: "lint"

  verify-format-and-lint:
    runs-on: ubuntu-latest
    needs: [check-want-lint]
    if: ${{ github.triggering_actor != 'dependabot[bot]' && (inputs.force || needs.check-want-lint.outputs.want-test == 'true') }}

    steps:
      - run: sudo apt-get install -y libeigen3-dev

      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.16.0" # for Ubuntu 20.04

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure with cmake
        run: |
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -S . -B build -G Ninja

      - name: Run clang tools to all files
        if: ${{ always() && !inputs.files-changed-only }}
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh

          VERS=${{ inputs.version }}
          sudo ./llvm.sh $VERS
          sudo apt-get install -y clang-tidy-$VERS clang-format-$VERS
          sudo ln -sf clang-tidy-$VERS /usr/bin/clang-tidy
          sudo ln -sf clang-format-$VERS /usr/bin/clang-format

          ./scripts/run_clang_tools.sh -c

      - uses: cpp-linter/cpp-linter-action@v2
        if: ${{ always() && inputs.files-changed-only }}
        id: clang-tools
        with:
          version: ${{ inputs.version }}
          extensions: "cpp,hpp,c,h"
          style: file
          tidy-checks: ""
          database: build
          ignore: ".github|build|third-party|test"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Fail fast
        if: ${{ always() && steps.clang-tools.outputs.checks-failed > 0 }}
        run: echo "Some files failed the linting checks!" && exit 1
