#
# Project NuriKit - Copyright 2025 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Build sdist

on:
  workflow_call:
    inputs:
      emulate-version:
        type: string
        description: "Version to emulate"
        required: false
        default: ""
    outputs:
      version:
        description: "The built sdist version"
        value: ${{ jobs.build.outputs.version }}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: "ubuntu-latest"

    outputs:
      version: ${{ steps.extract-version.outputs.version }}

    steps:
      - run: sudo apt-get install -y libeigen3-dev

      - uses: lukka/get-cmake@latest
        with:
          # Ubuntu 22.04
          cmakeVersion: "~3.22.0"

      - uses: actions/checkout@v4

      - name: Configure with cmake
        run: |
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DNURI_FORCE_VERSION="$nuri_version" \
            -S . -B build -G Ninja
        env:
          nuri_version: ${{ inputs.emulate-version }}

      - run: pipx run build --sdist

      - id: extract-version
        run: |
          echo "version=$(
            tar -O -xzf dist/*.tar.gz --wildcards '*/PKG-INFO' |
              sed -n -E 's/^version:[[:space:]]*([^[:space:]]+)/\1/Ip'
          )" >>"$GITHUB_OUTPUT"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*
