#
# Project NuriKit - Copyright 2025 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Build sdist

on:
  workflow_call:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - run: sudo apt-get install -y libeigen3-dev

      - uses: lukka/get-cmake@latest
        with:
          # Ubuntu 22.04
          cmakeVersion: "~3.22.0"

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure with cmake
        run: cmake -DCMAKE_BUILD_TYPE=Release -S . -B build -G Ninja

      - run: pipx run build --sdist

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*
