#
# Project nurikit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Test main branch

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/main-check.yaml"
      - ".github/workflows/_cpp-test-and-coverage.yaml"
      - "cmake/**"
      - "include/**"
      - "scripts/check_coverage.sh"
      - "src/**"
      - "test/**"
      - "third-party/**"
      - ".clang-*"
      - "CMakeLists.txt"

defaults:
  run:
    shell: bash

jobs:
  run-clang-tools:
    if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
    uses: ./.github/workflows/_run-clang-tools.yaml

  test-and-coverage:
    if: ${{ !contains(github.event.head_commit.message, '[skip test]') }}
    uses: ./.github/workflows/_cpp-test-and-coverage.yaml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
