#
# Project nurikit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Lint PR

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/pr-lint.yaml"
      - ".github/workflows/_run-clang-tools.yaml"
      - "scripts/run_clang_tools.sh"
      - "**.clang-*"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

defaults:
  run:
    shell: bash

jobs:
  run-clang-tools:
    uses: ./.github/workflows/_run-clang-tools.yaml
    with:
      files-changed-only: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
