#
# Project nurikit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: PR reviews for C++ files

on:
  pull_request:
    branches:
      - main
      - "release/**"
    paths:
      - ".github/workflows/pr-review-cpp.yaml"
      - ".github/workflows/test_and_coverage.yaml"
      - "cmake/**"
      - "scripts/check_coverage.sh"
      - "src/**"
      - "test/**"
      - "third-party/**"
      - ".clang-*"
      - "CMakeLists.txt"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

defaults:
  run:
    shell: bash

jobs:
  run-clang-tools:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.16.0" # for Ubuntu 20.04

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libboost-graph-dev

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure with cmake
        run: |
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -S . -B build

      - uses: cpp-linter/cpp-linter-action@v2
        id: clang-tools
        with:
          version: "15"
          extensions: "cpp,hpp,c,h"
          style: file
          tidy-checks: ""
          database: build
          ignore: ".github|build|third-party|test"
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Fail fast
        if: ${{ steps.clang-tools.outputs.checks-failed > 0 }}
        run: echo "Some files failed the linting checks!" && exit 1

  test-and-coverage:
    needs: [run-clang-tools]
    uses: ./.github/workflows/test_and_coverage.yaml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
