#
# Project NuriKit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Test PR

on:
  pull_request:
    branches:
      - main
      - "release/**"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

defaults:
  run:
    shell: bash

jobs:
  check-want-test:
    uses: ./.github/workflows/_check-want-test.yaml

  test-and-coverage:
    needs: check-want-test
    if: ${{ needs.check-want-test.outputs.want-test == 'true' }}
    uses: ./.github/workflows/_test-and-coverage.yaml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  conclusion:
    needs: test-and-coverage
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - run: |
          if [[ $FAILED == 'true' ]]; then
            echo "Test failed."
            exit 1
          fi
        env:
          FAILED: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
