#
# Project nurikit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Test PR

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/main-review.yaml"
      - ".github/workflows/_cpp-test-and-coverage.yaml"
      - "cmake/**"
      - "include/**"
      - "scripts/check_coverage.sh"
      - "src/**"
      - "test/**"
      - "third-party/**"
      - ".clang-*"
      - "CMakeLists.txt"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

defaults:
  run:
    shell: bash

jobs:
  get-commit-msg:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    outputs:
      commit-msg: ${{ steps.get-commit-msg.outputs.commit-msg }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get commit message
        id: get-commit-msg
        run: |
          MSG="$(git log --no-merges --format=%B -n 1 HEAD)"
          echo 'commit-msg<<EOM' >> $GITHUB_OUTPUT
          echo "commit-msg=${MSG}" >> $GITHUB_OUTPUT
          echo 'EOM' >> $GITHUB_OUTPUT

  test-and-coverage:
    needs: [get-commit-msg]
    if: ${{ !contains(needs.get-commit-msg.outputs.commit-msg, '[skip test]') }}
    uses: ./.github/workflows/_cpp-test-and-coverage.yaml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
