#
# Project NuriKit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Build test wheel for PR

on:
  pull_request:
    branches:
      - main
      - "release/**"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

defaults:
  run:
    shell: bash

jobs:
  check-want-test:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/_check-want-test.yaml

  test-build-wheels:
    needs: check-want-test
    if: ${{ needs.check-want-test.outputs.want-test == 'true' }}
    uses: ./.github/workflows/wheels-matrix.yaml
    with:
      minimal: true

  conclusion-wheels:
    needs: test-build-wheels
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - run: |
          if [[ $FAILED == 'true' ]]; then
            echo "Linting failed."
            exit 1
          fi
        env:
          FAILED: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
