#
# Project NuriKit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Build test wheel for PR

on:
  pull_request:
    branches:
      - main
      - "release/**"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

defaults:
  run:
    shell: bash

jobs:
  check-want-test:
    if: ${{ !github.event.pull_request.draft }}
    uses: ./.github/workflows/_check-want-test.yaml

  test-build-linux:
    needs: [check-want-test]
    if: ${{ needs.check-want-test.outputs.want-test == 'true' }}
    uses: ./.github/workflows/_wheel-build.yaml
    with:
      python: cp38-manylinux_x86_64

  test-build-mac-intel:
    needs: [check-want-test]
    if: ${{ needs.check-want-test.outputs.want-test == 'true' }}
    uses: ./.github/workflows/_wheel-build.yaml
    with:
      python: cp38-macosx_x86_64
      cpp_test: true

  test-build-mac-arm:
    needs: [check-want-test]
    if: ${{ needs.check-want-test.outputs.want-test == 'true' }}
    uses: ./.github/workflows/_wheel-build.yaml
    with:
      python: cp38-macosx_arm64
      cpp_test: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
