#
# Project nurikit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Test and Report Coverage

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

defaults:
  run:
    shell: bash

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.16.0" # for Ubuntu 20.04

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcovr

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Compile and run tests
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DNURIKIT_TEST_COVERAGE=ON -G Ninja ..
          cmake --build . -j --target nurikit_all_test
          ../scripts/check_coverage.sh . --xml

      # dependabot does not have access to CODECOV_TOKEN
      - uses: codecov/codecov-action@v3
        if: ${{ github.triggering_actor != 'dependabot[bot]' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/coverage/xml/coverage.xml
          fail_ci_if_error: true
          verbose: true
