#
# Project NuriKit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Build wheels in matrix

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      emulate-version:
        type: string
        description: "Version to emulate"
        required: false
        default: ""
      minimal:
        type: boolean
        description: "Minimal build"
        required: false
        default: false
  push:
    branches:
      - main
    paths:
      - ".github/scripts/build-lib.sh"
      - ".github/workflows/wheels-matrix.yaml"
      - ".github/workflows/_base-build.yaml"
      - ".github/workflows/_wheel-build.yaml"
      - "cmake/**"
      - "include/**"
      - "src/**"
      - "python/**"
      - "third-party/**"
      - "**/.clang-*"
      - "**/CMakeLists.txt"
      - pyproject.toml.in

defaults:
  run:
    shell: bash

jobs:
  common:
    uses: ./.github/workflows/_base-build.yaml
    with:
      emulate-version: ${{ inputs.emulate-version }}

  build-wheels:
    needs: common

    strategy:
      fail-fast: false
      matrix:
        pyver:
          - cp37
          - cp38
          - cp39
          - cp310
          - cp311
          - cp312
          - cp313
          - cp313t
        os: ["manylinux_x86_64", "macosx_x86_64", "macosx_arm64"]
        minimal:
          - ${{ inputs.minimal }}
        exclude:
          - pyver: "cp37"
            os: "macosx_arm64"
          - minimal: true
        include:
          - pyver: "cp38"
            os: "manylinux_x86_64"
          - pyver: "cp38"
            os: "macosx_x86_64"
          - pyver: "cp38"
            os: "macosx_arm64"

    uses: ./.github/workflows/_wheel-build.yaml
    with:
      python: ${{ matrix.pyver }}-${{ matrix.os }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
