#
# Project NuriKit - Copyright 2023 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: Build wheels in matrix

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/wheels-matrix.yaml"
      - ".github/workflows/_wheel-build.yaml"
      - "cmake/**"
      - "include/**"
      - "src/**"
      - "python/**"
      - "third-party/**"
      - "**/.clang-*"
      - "**/CMakeLists.txt"
      - pyproject.toml.in

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python: ["cp37", "cp38", "cp39", "cp310", "cp311", "cp312"]

    uses: ./.github/workflows/_wheel-build.yaml
    with:
      python: ${{ matrix.python }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
